spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: info

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  jwt:
    # couvre les deux cas de code: soit un secret unique, soit access/refresh distincts
    secret: ${APP_JWT_SECRET:}
    access-secret: ${APP_JWT_ACCESS_SECRET:${APP_JWT_SECRET:}}
    refresh-secret: ${APP_JWT_REFRESH_SECRET:${APP_JWT_SECRET:}}
    ttl-seconds: 86400
  centrifugo:
    api-base: ${CENTRIFUGO_API_BASE}
    api-key: ${CENTRIFUGO_HTTP_API_KEY}
    token-hmac-secret-key: ${CENTRIFUGO_HMAC_SECRET}
    token-ttl-seconds: 86400
    mission-namespace: ${APP_CENTRIFUGO_MISSION_NAMESPACE:missions}
    status-channel: ${APP_CENTRIFUGO_STATUS_CHANNEL:status}
